on: [push]

jobs:
  autotick-action:
    runs-on: ubuntu-latest
    name: autotick-action
    steps:
    - name: autotick-action
      id: aa
      uses: beckermr/autotick-github-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
