on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
  check_run:
    types:
      - completed

jobs:
  autotick-action:
    runs-on: ubuntu-latest
    name: autotick-action
    steps:
    - name: autotick-action
      id: aa
      uses: beckermr/autotick-github-action@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
