on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
  check_run:
    types:
      - completed
  # schedule:
  #   - cron:  '0 * * * *'
  # push: {}

jobs:
  regro-cf-autotick-bot-action:
    runs-on: ubuntu-latest
    name: regro-cf-autotick-bot-action
    steps:
    - name: regro-cf-autotick-bot-action
      id: regro-cf-autotick-bot-action
      uses: beckermr/autotick-github-action@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
